### ISSUE TITLE
绘制的时候是否不上屏，只在Framebuffer中绘制？

### ISSUE THREAD

**Issue by cangwang** [Tencent/tgfx#201]
if (tgfxWindow == nullptr) {
        tgfxWindow = tgfx::EGLWindow::Current();
    }
    if (tgfxWindow == nullptr) {
        return -1;
    }
    auto device = tgfxWindow->getDevice();
    auto context = device->lockContext();
    if (context == nullptr) {
        return -1;
    }
    auto tgfxSurface = tgfx::Surface::Make(context, width, height);
    if (tgfxSurface == nullptr) {
        device->unlock();
        return -1;
    }
    auto canvas = tgfxSurface->getCanvas();
    canvas->clear();
    canvas->save();

    //实体类绘制内容，如矩形，线条
    drawShape(frameInfo, canvas);

    canvas->restore();
    tgfxSurface->flush();
    tgfx::GLTextureInfo textureInfo;
    tgfxSurface->getBackendTexture().getGLTextureInfo(&textureInfo);
    device->unlock();
    glBindFramebuffer(GL_FRAMEBUFFER,0);
    YMLOGV("textureId %d", textureInfo.id);
    return textureInfo.id;
使用以上代码会直接让tgfx绘制内容直接上屏，不需要直接上屏

**Comment by cangwang** [comment]
if (!frameBuffer) {
        frameBuffer = make_shared<FrameBuffer>();
        frameBuffer->init(width, height);
    }

    tgfx::GLFrameBufferInfo glFrameBufferInfo;
    glFrameBufferInfo.id = frameBuffer->buffer;
    tgfx::BackendRenderTarget backendRenderTarget(glFrameBufferInfo, width, height);
    tgfxSurface = tgfx::Surface::MakeFrom(context, backendRenderTarget,
                                               tgfx::ImageOrigin::TopLeft);
用以上代码创建了tgfxSurface进行绘制，还是会出现立刻上屏的现象，并且无法绘制成功。

**Comment by domchen** [comment]
如果你上屏了，那是你传进来用来绘制的FrameBufferID就是关联到屏幕了。你要用个绑定到离屏纹理的FrameBufferID传进来，才会画到你指定的纹理上。或者直接传进来一个纹理ID让内部初始化FrameBuffer。你遇到的问题都是对OpenGL的基础使用不太熟悉。你现在的需求涉及了tgfx与自定义OpenGL渲染环境的交互，这样用的前提是你自己已经能独立用OpenGL绘制一个简单的离屏图形，没有tgfx也能跑通流程，然后再来使用tgfx就没有任何理解上的障碍了。这块建议自己谷歌相关OpenGL教程补上，OpenGL的基础知识不会再作回复。
