### ISSUE TITLE
如何能够离屏渲染，不上屏的情况下从tgfx获取到纹理

### ISSUE THREAD

**Issue by cangwang** [Tencent/tgfx#202]
tgfx中只要调用tgfxSurface->flush();
 或者 
 tgfx::GLTextureInfo textureInfo;
    tgfxSurface->getBackendTexture().getGLTextureInfo(&textureInfo);
纹理就会直接上屏显示。我只需要离屏幕获取到tgfx里面的纹理

**Comment by domchen** [comment]
https://github.com/Tencent/tgfx/discussions/194

**Comment by cangwang** [comment]
渲染完flush后执行getBackendTexture()还是会直接上屏，我并不需要直接上屏。
