### ISSUE TITLE
渲染完flush后执行getBackendTexture()还是会直接上屏，我并不需要直接上屏，需要如何处理？

### ISSUE THREAD

**Issue by cangwang** [Tencent/tgfx#203]
渲染完flush后执行getBackendTexture()还是会直接上屏，我并不需要直接上屏。

_Originally posted by @cangwang in https://github.com/Tencent/tgfx/issues/202#issuecomment-2119094115_

**Comment by domchen** [comment]
注意看回复：关键是「通过宽高创建Surface」你哪来的直接上屏能力？

**Comment by domchen** [comment]
另外不要再通过Issue提使用问题了，这里是记录Bug的，在Disscusion提问。

**Comment by cangwang** [comment]
在屏幕的WIndows上获取Surface，途中使用FrameBuffer截取纹理后，并不会直接上屏。需要从FrameBuffer取出纹理后自行处理。这是Opengl的基础知识。

**Comment by domchen** [comment]
> 在屏幕的WIndows上获取Surface，途中使用FrameBuffer截取纹理后，并不会直接上屏。需要从FrameBuffer取出纹理后自行处理。这是Opengl的基础知识。

你对OpenGL里FrameBuffer的和离屏渲染的概念理解全都是错的，并不存在你说的什么从FrameBuffer截取纹理阻止上屏这种事情。FrameBuffer绑定到哪里就决定了渲染到哪里。你绑定到屏幕了结果就是渲染到屏幕。要绑定到离屏自己创建的纹理ID才是离屏的。
