### ISSUE TITLE
macOS 运行Hello2D crash

### ISSUE THREAD

**Issue by cgeffect** [Tencent/tgfx#207]
字体注册返回nullptr, 这个字体我电脑上是已经安装了的
![image](https://github.com/Tencent/tgfx/assets/15692322/0182190f-fd9d-4290-afac-d417e7eb5f4f)
而且在SimpleText里面使用的时候, 取的是"default"这个字符串, 但是外面使用的人, 并不知道要填default, 如果填了其他值, 岂不是和底层对不上了?
![image](https://github.com/Tencent/tgfx/assets/15692322/5a883af3-ac2b-4567-8a8e-60632581a828)
macos平台没有实现字体注册的功能
![image](https://github.com/Tencent/tgfx/assets/15692322/8c411cca-1177-4536-8fef-b5b8fa442f38)

## Which Version of tgfx are you using?

1.1.2

## What Platform are you on? 

 macOS 14.3.1 (23D60)

## build cmd
./gen_mac -DTGFX_USE_FREETYPE=ON

**Comment by domchen** [comment]
1.你有没注意看这个AppHost是哪里的类？它是业务代码，这个Demo工程里自己定义的简单注册机制，不是TGFX里的。所以没有你说的那个问题，你自己的程序只会直接使用Typeface。没有这个AppHost。

2.Mac平台是可以从字体名称创建Typeface的，因为Mac平台直接包装的CTFont对象。你之所以创建不出来，是因为名称用错了。mac平台想要定位系统安装的字体名称并不是用familyName+style这种分段式，而是一个组合的postscritname，直接通过Typeface::MakeFromName()的第一个参数传进去，第二个参数传递什么都会忽略无所谓。具体你可以自己找一下mac原生的CTFont创建字体用什么名称，用原生代码写一遍测设成功了，这里就是一样的成功。你想访问的是系统自带字体，这个名称匹配规则就得按照平台规定的来，没法修改。
