### ISSUE TITLE
安卓平台使用显示不出来

### ISSUE THREAD

**Issue by xzpqjew** [Tencent/tgfx#46]
## Which Version of tgfx are you using?

1.0.0

## What Platform are you on? 

Android 11

## Expected Behavior 

你好请问，，我模仿项目中的demo，新建了个android工程，链接了编译出来的tgfx.a，new了一个textureview，把surface传了进去，然后获取了windows device surface对象，draw了示例中的背景，但是没有任何显示，请问这个问题是哪里使用不对吗？或者有没有android平台下渲染图片或者文字的demo? 或者相关的接口使用文档？

![4](https://github.com/Tencent/tgfx/assets/37336674/ffd376b5-0d00-4cdd-a7e1-592c419b8093)

![5](https://github.com/Tencent/tgfx/assets/37336674/2ba3a663-8428-4c05-a0f3-e789cb7b5522)

**Comment by domchen** [comment]
issues我们只用来记录bug，使用问题请到discussions提问。安卓demo运行起来你点击一下屏幕就会看到文字和图片的示例，注意看项目里的代码逻辑。你现在有一个可以成功运行的项目，只是对比找不同这种工作需要自己完成。
